language: python
sudo: false
env:
  global:
  - HELM_URL=https://storage.googleapis.com/kubernetes-helm
  - HELM_TARBALL=helm-v2.9.1-linux-amd64.tar.gz
  - STABLE_REPO_URL=https://phucvd.storage.googleapis.com/
  - INCUBATOR_REPO_URL=https://phucvd-incubator.storage.googleapis.com/
  - GCS_BUCKET_STABLE=gs://phucvd
  - GCS_BUCKET_INCUBATOR=gs://phucvd-incubator
  - ALLOW_OVERWRITE_INDEX_FILE=true
before_install:
- git submodule update --init --recursive
- openssl aes-256-cbc -K $encrypted_cbce4ac2ef86_key -iv $encrypted_cbce4ac2ef86_iv
  -in credential.json.enc -out credential.json -d
install:
- wget -q ${HELM_URL}/${HELM_TARBALL}
- tar xzfv ${HELM_TARBALL}
- PATH=`pwd`/linux-amd64/:$PATH
- helm init --client-only
- if [ ! -d ${HOME}/google-cloud-sdk ]; then export CLOUDSDK_CORE_DISABLE_PROMPTS=1;
  curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
before_script:
- git config --global user.name "Phuc Bot"
- git config --global user.email "phucvd.ce@gmail.com"
- chmod ugo+x ./.travis/sync-repo.sh
script:
- |
  # Check format helm stable
  for dir in `find stable/* -type d`; do 
    helm lint $dir
    if [ $? != 0 ]; then 
      travis_terminate 1 
    fi 
  done 
  # Check format helm incubator
  for dir in `find incubator/* -type d`; do 
    helm lint $dir
    if [ $? != 0 ]; then 
      travis_terminate 1 
    fi 
  done 
after_success:
- |
  #if [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then
  ./.travis/sync-repo.sh
  #fi
notifications:
  slack:
    rooms:
      secure: "e6XGYFTDrZpQv2tf9yZfmh1CICmnYrVg/k19qes/akA8FZPJDtiPdYIKWI2+mcsuh8qgF3X67iHSN3EtbUrhNcF57SchQ+oEK31wbNDaf+vT7ToTya4mXxamAGJtLwL3C6OtPyViFr8AmLRFtIiSMiEVv+WCDMvz6Iqrzvq+qn3iItqacf/Bn/7Co8ynUPiJ5i8lAw5kDwJJtFH0LaAyyKr7QyrRFTj7V3G3NTKFX68++W+WWxPBuan8WtgiUPT1OEVH8o+zDlDJmh/qGTLb1N8wkQTzQOfFpNoR6IdXBmV6+E6gb88Nlv5kmcYtMWqrKQwI7BWrjqviVj19TQZPxhjpG7tdy0MMPErilnRqiUSP/fdqLc1OR4zRqa8ZkUTVd1Z1G+iO/a57m1y7+SksERr49s/cgEj45Qt+r/wk9l0xBUxUNYzLNpCdHhnehsQ+s3oT1NnbNarANWa63UoaCInjs4hr8XMnvXAvoCHYwJp4Z5I7HI0sqQaMXxoQtsaOVOmSTvqNFpMDnHADqcwVZCQXH8TiJ3xoiyhE6QeJ/fMFoeVaJW5p1U0vZVW+9SHVQ8ivO9vMhhqoEI3gz2WRkZORTU5aGq/n5PQnUeS/slpjmB/Yt7Yz1XZkwVkkwW6vXmU9ku+FDB2g39eShIzHIRYhsRL7RY1U/xTLt6skNS0="
    on_success: always
