language: python
sudo: false
env:
  global:
  - HELM_URL=https://storage.googleapis.com/kubernetes-helm
  - HELM_TARBALL=helm-v2.9.1-linux-amd64.tar.gz
  - STABLE_REPO_URL=https://phucvd.storage.googleapis.com/
  - INCUBATOR_REPO_URL=https://phucvd-incubator.storage.googleapis.com/
  - GCS_BUCKET_STABLE=gs://phucvd
  - GCS_BUCKET_INCUBATOR=gs://phucvd-incubator
before_install:
- git submodule update --init --recursive
# Decrypt the credentials we added to the repo using the key we added with the Travis command line tool
- openssl aes-256-cbc -K $encrypted_cbce4ac2ef86_key -iv $encrypted_cbce4ac2ef86_iv -in credential.json.enc -out credential.json -d
install:
- wget -q ${HELM_URL}/${HELM_TARBALL}
- tar xzfv ${HELM_TARBALL}
- PATH=`pwd`/linux-amd64/:$PATH
- helm init --client-only
#- pip install gsutil
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     curl https://sdk.cloud.google.com | bash;
  fi
before_script:
- git config --global user.name "Phuc Bot"
- git config --global user.email "phucvd.ce@gmail.com"
- chmod ugo+x ./.travis/sync-repo.sh
script:
- |
  # Check Stable folder 
  for dir in `ls -d ./stable/*/`; do
   helm lint $dir
   if [ $? != 0 ]; then
    travis_terminate 1
   fi
  done
  # Check Incubator folder 
  for dir in `ls -d ./incubator/*/`; do
   helm lint $dir
   if [ $? != 0 ]; then
    travis_terminate 1
   fi
  done
after_success:
- |
  #if [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then
  ./.travis/sync-repo.sh
  #fi
notifications:
  email: false
  slack:
    room:
      secure: gZQxS4eKq3bLZrWCYpG7ujefJF07yTccGhsV0zK4HPq2go849wbpF9btJnltQFd/GbWWNe2+mDEO9ca6kAnY9TOwLLcS99TNL0ev+ene3uC5OgAYvzniy2LYO7LouJx0GGnaKdQFafhePLD1pnsvKwy8lD7X0brPhEmn8A7F3DSpkV+SvXejf22YtTd0AuJL+gBXXj+wOHzthmL1p37FtSicMZe/1SgiUX22ZX+Y1bJ6k/AwvIQTG0ixN2KE5b4eGFwLCoG32rK/7GUVbcNK7tYlI9gVyYNfqreBbtvl1Oz5SuZrrD1tYjlCTZimX6CWiCxPef7SU2a9ZzDXdtnP6HHb+QLE5Vt6fO/NDAtw1XlLBQd/W6iymruE4RawykJKp6QZYlYxTj+qu+YSMyrwjbmerxlNU24c7WKEhF1ZTarKM4b3K3MsgH24TsG8wIDSClWYtP0pbyVgdg1IT4QeqpEswMEU4OFc5pgoLgE/w0olU3ikBsGMjokHTK7u4LPPhqOrrE7kG0e605z0upByigv0hTVOXcVD1wYXcoGGXaKr4LYKBfi4UEqxxIdtrq2DPMlzTsm8LmHJM0VjmF2czTWL1Sr+8AmLH0dHWFLYtoozcAHKfGzqAzfWe8ZR1qHj7o4TfFN1FE/S4J5YrNxfrLKzD763llk5MnwCAnFfHY0=
    on_success: change # default: always
    on_failure: always # default: always