language: python
sudo: false
env:
  global:
  - HELM_URL=https://storage.googleapis.com/kubernetes-helm
  - HELM_TARBALL=helm-v2.9.1-linux-amd64.tar.gz
  - STABLE_REPO_URL=https://teracyhq.storage.googleapis.com/
  - INCUBATOR_REPO_URL=https://teracyhq-incubator.storage.googleapis.com/
  - GCS_BUCKET_STABLE=gs://teracyhq
  - GCS_BUCKET_INCUBATOR=gs://teracyhq-incubator
  - ALLOW_OVERWRITE_INDEX_FILE=true
before_install:
- git submodule update --init --recursive
#Please replace the following line with your credential command
- openssl aes-256-cbc -K $encrypted_cbce4ac2ef86_key -iv $encrypted_cbce4ac2ef86_iv
  -in credential.json.enc -out credential.json -d
install:
- wget -q ${HELM_URL}/${HELM_TARBALL}
- tar xzfv ${HELM_TARBALL}
- PATH=`pwd`/linux-amd64/:$PATH
- helm init --client-only
- if [ ! -d ${HOME}/google-cloud-sdk ]; then export CLOUDSDK_CORE_DISABLE_PROMPTS=1;
  curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
before_script:
- git config --global user.name "<Replace your name here>"
- git config --global user.email "<Replace your email here>"
- chmod ugo+x ./.travis/sync-repo.sh
script:
- |
  # Check format helm stable
  for dir in `find stable/ -mindepth 1 -maxdepth 1 -type d`; do 
    helm lint $dir
    if [ $? != 0 ]; then 
      travis_terminate 1 
    fi 
  done 
  # Check format helm incubator
  for dir in `find incubator/ -mindepth 1 -maxdepth 1 -type d`; do 
    helm lint $dir
    if [ $? != 0 ]; then 
      travis_terminate 1 
    fi 
  done 
after_success:
- |
  if [ $TRAVIS_BRANCH == 'master' ] && [ $TRAVIS_PULL_REQUEST == 'false' ]; then
    ./.travis/sync-repo.sh
  fi
notifications:
  slack:
    rooms:
      secure: "<replace your slack channel's secure key here>"
    on_success: always
