apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "duplicity.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "duplicity.name" . }}
    helm.sh/chart: {{ include "duplicity.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- range $key, $val := .Values.configMap }}
  {{ $key }}: {{ default "" $val | quote }}
{{- end }}
