#!/usr/bin/env bash

export ZALENIUM_K8S_NAMESPACE=hieptq
export ZALENIUM_HELM_REVISION=1
export ZALENIUM_HELM_CHART_PATH=zalenium
export ZALENIUM_RELEASE_NAME=teracy-zalenium

# app args
export ZALENIUM_HUB_DESIRED_CONTAINERS=2
export ZALENIUM_HUB_MAX_DOCKER_SELENIUM_CONTAINER=5
export ZALENIUM_HUB_VIDEO_RECORD_ENABLE=true
export ZALENIUM_HUB_SCREEN_WIDTH=1440
export ZALENIUM_HUB_SCREEN_HEIGHT=900
export ZALENIUM_HUB_TIME_ZONE=UTC
export ZALENIUM_HUB_SELENIUM_IMAGE=elgalu/selenium
export ZALENIUM_HUB_MAX_TEST_SESSIONS=2
export ZALENIUM_HUB_DEBUG_ENABLE=true
export ZALENIUM_HUB_KEEP_FAILED_TEST=false
export ZALENIUM_HUB_SEND_USAGE=false
export ZALENIUM_HUB_LOG_JSON_FORMAT=true

# ingress
export ZALENIUM_INGRESS_ENABLED=true
export ZALENIUM_HUB_HOST=<set-your-domain> # no need http://
