{{- $fullName := include "fullname" . -}}
{{- range $key, $val := .Values.mountStorage }}
{{- if and (.enabled) (.pvcs.enabled) (not .pvcs.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $fullName }}-{{ $key }}
  labels:
    app: {{ $fullName }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
spec:
  accessModes:
    - {{  .pvcs.accessMode | quote }}
  resources:
    requests:
      storage: {{  .pvcs.size | quote }}
{{- if  .pvcs.storageClass }}
{{- if (eq "-"  .pvcs.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{  .pvcs.storageClass }}"
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}