{{- $fullName := include "fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if not ( empty .Values.services.serviceAnnotations) }}
  annotations:
{{ toYaml .Values.services.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.services.type }}
  sessionAffinity: {{ .Values.services.serviceSessionAffinity | quote }}
  ports:
    - name: {{ .Values.hub.name }}
      protocol: TCP
      port: {{ .Values.services.port }}
      targetPort: {{ .Values.services.targetPort }}
      {{- if .Values.services.nodePort }}
      nodePort: {{ .Values.services.nodePort }}
      {{- end }}
  selector:
    app: {{ $fullName }}
    zalenium: {{ .Values.hub.name }}
