{{- $fullName := include "fullname" . -}}
{{- range $key, $val := .Values.pvcs }}
{{- if and $val.enabled (not $val.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}-{{ $key }}
  labels:
    app: {{ $fullName }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
spec:
  accessModes:
    - {{ $val.accessMode | quote }}
  resources:
    requests:
      storage: {{ $val.size | quote }}
{{- if $val.storageClass }}
{{- if (eq "-" $val.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ $val.storageClass }}"
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}