{{- range .Values.ingress.tls }}
{{- if and .enabled .tlsCrtName  .tlsKeyName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  labels:
    app: {{ template "name" $ }}
    chart: {{ template "chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
type: kubernetes.io/tls
data:
{{- $tlsCrtPath := cat "config/" .tlsCrtName | replace " " "" }}
{{- $tlsKeyPath := cat "config/" .tlsKeyName | replace " " "" }}
  tls.crt: {{ $.Files.Get $tlsCrtPath | b64enc }}
  tls.key: {{ $.Files.Get $tlsKeyPath | b64enc }}
---
{{- end }}
{{- end }}
